version: "3.9"

services:
  rentigo-dev-db:
    image: postgres:${POSTGRES_DEV_VERSION}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DEV_DB}
      POSTGRES_USER: ${POSTGRES_DEV_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEV_PASSWORD}
    volumes:
      - rentigo-dev-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  rentigo-dev:
    driver: bridge

volumes:
  rentigo-dev-data:
