name: BasicCI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
    with:
      number-of-agents: 4
      parallel-commands: |
        npx nx-cloud record -- npx nx lint
        npx nx-cloud record -- npx nx test
        npx nx-cloud record -- npx nx build
        npx nx-cloud record -- npx nx run frontend-e2e:e2e
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=4
        npx nx affected --target=test --parallel=4 --ci --code-coverage
        npx nx affected --target=build --parallel=4
        npx nx run frontend-e2e:e2e --parallel=4

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
    with:
      number-of-agents: 4
