name: BasicCI

on:
  push:
    branches:
      - main
  pull_request:

env:
  JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "LINT"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run lint:all
      - run: npm run lint:affected
  build:
    runs-on: ubuntu-latest
    name: "BUILD"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run build:all
      - run: npm run build:affected
  test:
    runs-on: ubuntu-latest
    name: "TEST"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run test:all
      - run: npm run test:affected
  # e2e:
  #   runs-on: ubuntu-latest
  #   name: "e2e"
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  # 	    fetch-depth: 0
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         cache: "npm"
  #         cache-dependency-path: package-lock.json
  #     - run: npm ci
  #     - uses: cypress-io/github-action@v4
  #     - run: npm run e2e:all
  #     - run: npm run e2e:affected
